project:

  type: website

  output-dir: docs



website:

  title: "From 8-Bit Loops to Cinematic Scores"

  navbar:

    left:

      - href: index.qmd

        text: Home

      - href: data.qmd

        text: Data

      - href: analysis.qmd

        text: Analysis

      - href: listening.qmd

        text: Listening

      - href: conclusion.qmd

        text: Conclusion



format:

  html:

    theme: lux

    toc: true

    page-layout: full

    css: styles.css